name: "Podcast Generator"
auther: "Saurab Nand"
description: "Generate a podcast episode from a given topic using OpenAI's GPT-3.5-turbo model."
runs: 
  using: "docker"
  image: "Dockerfile"
branding: 
  icon: "git-branch"
  color: "red
inputs:
  email: 
    description: "Email address to send the podcast episode to."
    required: true
    default: ${{ github.actor }}@localhost
    name: 
    required: true
    default: ${{ github.actor }}