name: "Podcast Generator"
author: "Saurab Nand"
description: "Generate a podcast episode from a given topic using OpenAI's GPT-3.5-turbo model."

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "git-branch"
  color: "red"

inputs:
  email:
    description: "Email address to send the podcast episode to."
    required: true
    default: "${{ github.actor }}@localhost"
  name:
    description: "Name of the person requesting the podcast."
    required: true
    default: "${{ github.actor }}"